### ISSUE TITLE
hexdump module not found

### ISSUE THREAD

**Issue by modz2014** [n0fate/chainbreaker#10]
Traceback (most recent call last):
  File "chainbreaker.py", line 27, in <module>
    from hexdump import hexdump
ImportError: No module named hexdump

yes python and pip are installed I tried to figure this out but no luck

**Comment by tommyyama2020** [comment]
Hi, I have a same issue with yours after upgrading mac OS to Catalina.

**Comment by n0fate** [comment]
@tommyyama2020  Catalina has Python 2 and 3. You need to install hexdump on Python 2.x

    $ pip2 install hexdump

**Comment by dylanahsmith** [comment]
It looks like `from hexdump import hexdump` has been removed.  So should this issue be closed now?

**Comment by modz2014** [comment]
Still doesn’t work same errror

**Comment by n0fate** [comment]
Sorry for being late. From now, no needs to hexdump modle. checkout #21
