### ISSUE TITLE
ImportError: No module named Crypto.Util

### ISSUE THREAD

**Issue by badrogh** [n0fate/chainbreaker#14]
Hello there, 
I have an issue attempting to open the login.keychain-db

`mbp:chainbreaker admin$ python2 chainbreaker.py -f login.keychain-db -p ********`
`Traceback (most recent call last):`
`  File "chainbreaker.py", line 35, in <module>`
`    from validator import Validator`
`  File "/Users/admin/chainbreaker/validator.py", line 2, in <module>`
`    from Crypto.Util import asn1`
`ImportError: No module named Crypto.Util`
`mbp:chainbreaker admin$ `

Yes I know the keychain database is to be grabbed from User's library, I just made a local copy of it.
For what it's worth, I am running MacOS 10.15.3 (Catalina)

Any idea how to debug this?
Thanks

Edit: made the output cleaner

**Comment by alatas** [comment]
I had the same issue. It seemsthe pip command installs the pycrypto to python 3 not 2. I reinstalled pip on python2, then pycrypto. 

https://github.com/Homebrew/legacy-homebrew/issues/50607

**Comment by badrogh** [comment]
Teşekkür Sukru. Nicely spotted.
