### ISSUE TITLE
macOS Monterey Public Key Table is not available

### ISSUE THREAD

**Issue by tenwx** [n0fate/chainbreaker#23]
sudo python chainbreaker.py --unlock-file ./SystemKey -a -e /Library/Keychains/System.keychain

...
2022-02-23 17:55:10,160 - INFO - Dump Start: 2022-02-23 17:55:10.159697
private_key_offset2022-02-23 17:55:10,625 - WARNING - 23596
private_key_offset2022-02-23 17:55:10,625 - WARNING - 23596
private_key_offset2022-02-23 17:55:10,625 - WARNING - 23596
private_key_offset2022-02-23 17:55:10,625 - WARNING - 23596
2022-02-23 17:55:10,625 - WARNING - [!] Public Key Table is not available
...

Is Monterey(12.2.1) not support yet?

**Comment by n0fate** [comment]
Sorry for being late. I fix some code for this issues. checkout #21
